#include "DNAKernel.h"
#include <stdatomic.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define VOICES 32
#define TAU 6.283185307179586
#define MIN(a,b) ((a)<(b)?(a):(b))
#define MAX(a,b) ((a)>(b)?(a):(b))
typedef struct {int present,struck;float attack,decay,release,harmonics[12];int harmonic_count;float *sample;uint32_t length;double rate;} Anchor;
struct DNABank {Anchor anchors[DNA_LAYERS][128];struct DNABank *next;};
typedef struct {atomic_uint revision;atomic_int midi,down,physical_down;_Atomic float velocity,bend;atomic_uint order;} Slot;
typedef struct {int slot,midi,layer,root,releasing,struck;unsigned revision;double phase,position,age,hz,target;float velocity,envelope,filtered;const Anchor *anchor;} Voice;
struct DNAKernel {double rate;_Atomic float parameters[DNA_PARAMETER_COUNT];Slot slots[DNA_SLOT_COUNT];unsigned seen[DNA_SLOT_COUNT];atomic_uint clock;Voice voices[VOICES];_Atomic(DNABank*) bank;_Atomic(DNABank*) hazard;DNABank *retired;uint32_t random;atomic_int pedal[16];int previous_mode;float era_left,era_right;};
static float clamp(float v,float lo,float hi){return MIN(hi,MAX(lo,v));}
DNAKernel *dna_kernel_create(double rate){DNAKernel*k=calloc(1,sizeof(*k));if(!k)return NULL;k->rate=rate;k->random=101;atomic_init(&k->clock,0);atomic_init(&k->bank,NULL);atomic_init(&k->hazard,NULL);for(int i=0;i<16;i++)atomic_init(&k->pedal[i],0);for(int i=0;i<DNA_SLOT_COUNT;i++){atomic_init(&k->slots[i].revision,0);atomic_init(&k->slots[i].midi,60);atomic_init(&k->slots[i].down,0);atomic_init(&k->slots[i].physical_down,0);atomic_init(&k->slots[i].velocity,0);atomic_init(&k->slots[i].bend,0);atomic_init(&k->slots[i].order,0);}for(int i=0;i<VOICES;i++)k->voices[i].slot=-1;for(int i=0;i<DNA_PARAMETER_COUNT;i++)atomic_init(&k->parameters[i],i<14?.5f:0);dna_parameter_set(k,DNA_VOLUME,.7f);dna_parameter_set(k,DNA_BEND_RANGE,2);dna_parameter_set(k,DNA_GLIDE,70);dna_parameter_set(k,DNA_TRILL_RATE,7);dna_parameter_set(k,DNA_TRILL_INTERVAL,1);dna_parameter_set(k,DNA_TRILL_THRESHOLD,100);return k;}
void dna_bank_destroy(DNABank*b){if(!b)return;for(int l=0;l<DNA_LAYERS;l++)for(int n=0;n<128;n++)free(b->anchors[l][n].sample);free(b);}
void dna_kernel_destroy(DNAKernel*k){if(!k)return;dna_bank_destroy(atomic_load(&k->bank));while(k->retired){DNABank*b=k->retired;k->retired=b->next;dna_bank_destroy(b);}free(k);}
void dna_kernel_set_rate(DNAKernel*k,double rate){if(rate>=8000&&rate<=192000)k->rate=rate;}
void dna_parameter_set(DNAKernel*k,int p,float v){if(p<0||p>=DNA_PARAMETER_COUNT||!isfinite(v))return;float lo=0,hi=1;if(p==DNA_PITCH)lo=-1;if(p==DNA_BEND_RANGE)hi=48;if(p==DNA_VOICE_MODE||p==DNA_ERA)hi=2;if(p==DNA_GLIDE){lo=10;hi=250;}if(p==DNA_LAYER)hi=5;if(p==DNA_TRILL_RATE){lo=3;hi=15;}if(p==DNA_TRILL_INTERVAL){lo=1;hi=12;}if(p==DNA_TRILL_THRESHOLD){lo=1;hi=127;}if(p==DNA_NOTE_LENGTH)hi=15;if(p==DNA_ENGINE_MODE)hi=3;atomic_store(&k->parameters[p],clamp(v,lo,hi));}
float dna_parameter_get(DNAKernel*k,int p){return p>=0&&p<DNA_PARAMETER_COUNT?atomic_load(&k->parameters[p]):0;}
void dna_note_set(DNAKernel*k,int slot,int midi,float velocity,int down){if(slot<0||slot>=DNA_SLOT_COUNT||midi<0||midi>127)return;Slot*s=&k->slots[slot];atomic_store(&s->midi,midi);atomic_store(&s->velocity,clamp(velocity,0,1));atomic_store(&s->down,!!down);if(down)atomic_store(&s->order,atomic_fetch_add(&k->clock,1)+1);atomic_fetch_add(&s->revision,1);}
void dna_note_bend(DNAKernel*k,int slot,float bend){if(slot>=0&&slot<DNA_SLOT_COUNT)atomic_store(&k->slots[slot].bend,clamp(bend,-48,48));}
void dna_all_notes_off(DNAKernel*k){for(int c=0;c<16;c++)atomic_store(&k->pedal[c],0);for(int i=0;i<DNA_SLOT_COUNT;i++){atomic_store(&k->slots[i].down,0);atomic_store(&k->slots[i].physical_down,0);atomic_store(&k->slots[i].bend,0);atomic_fetch_add(&k->slots[i].revision,1);}}
void dna_midi(DNAKernel*k,uint8_t status,uint8_t a,uint8_t b){int type=status&0xf0,channel=status&15;if(type==0x90||type==0x80){int slot=DNA_TOUCH_SLOTS+channel*128+a;int down=type==0x90&&b>0;atomic_store(&k->slots[slot].physical_down,down);if(down||!atomic_load(&k->pedal[channel]))dna_note_set(k,slot,a,b/127.f,down);}else if(type==0xe0){float normalized=((int)b*128+a-8192)/8192.f;if(channel==0)dna_parameter_set(k,DNA_PITCH,normalized);else for(int n=0;n<128;n++)dna_note_bend(k,DNA_TOUCH_SLOTS+channel*128+n,normalized*dna_parameter_get(k,DNA_BEND_RANGE));}else if(type==0xb0){if(a==64){atomic_store(&k->pedal[channel],b>=64);if(b<64)for(int n=0;n<128;n++){int slot=DNA_TOUCH_SLOTS+channel*128+n;if(!atomic_load(&k->slots[slot].physical_down))dna_note_set(k,slot,n,0,0);}}if(a==1)dna_parameter_set(k,DNA_MODULATION,b/127.f);if(a==120||a==123)dna_all_notes_off(k);} (void)channel;}
DNABank*dna_bank_create(void){return calloc(1,sizeof(DNABank));}
int dna_bank_anchor(DNABank*b,int layer,int midi,float attack,float decay,float release,const float*h,int count,int struck){if(!b||layer<0||layer>=DNA_LAYERS||midi<0||midi>127)return 0;Anchor*a=&b->anchors[layer][midi];a->present=1;a->struck=struck;a->attack=clamp(attack,.001,2);a->decay=clamp(decay,.04,15);a->release=clamp(release,.005,5);a->harmonic_count=MIN(12,MAX(0,count));for(int i=0;i<a->harmonic_count;i++)a->harmonics[i]=isfinite(h[i])?clamp(h[i],0,1):0;return 1;}
int dna_bank_sample(DNABank*b,int layer,int midi,const float*mono,uint32_t length,double rate){if(!b||!mono||layer<0||layer>=DNA_LAYERS||midi<0||midi>127||length<16||length>rate*15||rate<8000||rate>192000)return 0;float*copy=malloc(length*sizeof(float));if(!copy)return 0;for(uint32_t i=0;i<length;i++)copy[i]=isfinite(mono[i])?clamp(mono[i],-4,4):0;Anchor*a=&b->anchors[layer][midi];free(a->sample);a->sample=copy;a->length=length;a->rate=rate;a->present=1;if(a->attack==0){a->attack=.01;a->decay=1;a->release=.12;}return 1;}
void dna_bank_publish(DNAKernel*k,DNABank*b){DNABank*old=atomic_exchange(&k->bank,b);if(old){old->next=k->retired;k->retired=old;}DNABank**link=&k->retired;while(*link){DNABank*item=*link;if(item!=atomic_load(&k->hazard)){*link=item->next;dna_bank_destroy(item);}else link=&item->next;}}
static const Anchor*anchor_for(DNABank*b,int layer,int midi,int*root){if(!b)return NULL;int best=-1;for(int n=0;n<128;n++)if(b->anchors[layer][n].present&&(best<0||abs(n-midi)<abs(best-midi)))best=n;if(best<0&&layer!=0)return anchor_for(b,0,midi,root);if(best<0)return NULL;*root=best;return &b->anchors[layer][best];}
static void start_voice(DNAKernel*k,Voice*v,int slot,DNABank*b,float*p,int legato){int midi=atomic_load(&k->slots[slot].midi),layer=(int)p[DNA_LAYER];float vel=atomic_load(&k->slots[slot].velocity);if(p[DNA_VELOCITY_TRILL]>.5f&&vel*127>=p[DNA_TRILL_THRESHOLD])layer=1;layer=MAX(0,MIN(5,layer));double hz=440*pow(2,(midi-69)/12.);if(!legato||v->slot<0){memset(v,0,sizeof(*v));v->hz=hz;}v->slot=slot;v->midi=midi;v->layer=layer;v->target=hz;v->velocity=vel;v->releasing=0;int root=midi;v->anchor=anchor_for(b,layer,midi,&root);v->root=root;v->struck=(v->anchor&&v->anchor->struck)||(int)p[DNA_ENGINE_MODE]==3;v->revision=atomic_load(&k->slots[slot].revision);}
static void sync_notes(DNAKernel*k,DNABank*b,float*p){int mode=(int)p[DNA_VOICE_MODE];if(mode!=k->previous_mode){for(int j=0;j<VOICES;j++)k->voices[j].slot=-1;memset(k->seen,0,sizeof(k->seen));k->previous_mode=mode;}if(mode>0){int chosen=-1;unsigned order=0;for(int i=0;i<DNA_SLOT_COUNT;i++)if(atomic_load(&k->slots[i].down)&&atomic_load(&k->slots[i].order)>=order){chosen=i;order=atomic_load(&k->slots[i].order);}for(int i=1;i<VOICES;i++)k->voices[i].slot=-1;Voice*v=&k->voices[0];if(chosen>=0&&(v->slot!=chosen||v->revision!=atomic_load(&k->slots[chosen].revision)))start_voice(k,v,chosen,b,p,mode==2&&v->slot>=0&&!v->releasing);else if(chosen<0&&v->slot>=0)v->releasing=1;return;}
for(int i=0;i<DNA_SLOT_COUNT;i++){unsigned rev=atomic_load(&k->slots[i].revision);if(rev==k->seen[i])continue;k->seen[i]=rev;Voice*v=NULL;for(int j=0;j<VOICES;j++)if(k->voices[j].slot==i){v=&k->voices[j];break;}if(!atomic_load(&k->slots[i].down)){if(v&&!v->struck)v->releasing=1;continue;}if(!v){for(int j=0;j<VOICES;j++)if(k->voices[j].slot<0){v=&k->voices[j];break;}if(!v){v=&k->voices[0];for(int j=1;j<VOICES;j++)if(k->voices[j].age>v->age)v=&k->voices[j];}}start_voice(k,v,i,b,p,0);}}
void dna_render(DNAKernel*k,float*left,float*right,uint32_t frames){float p[DNA_PARAMETER_COUNT];for(int i=0;i<DNA_PARAMETER_COUNT;i++)p[i]=atomic_load(&k->parameters[i]);DNABank*b;do{b=atomic_load(&k->bank);atomic_store(&k->hazard,b);}while(b!=atomic_load(&k->bank));for(int i=0;i<VOICES;i++)if(k->voices[i].anchor&&b){int root=k->voices[i].midi;k->voices[i].anchor=anchor_for(b,k->voices[i].layer,k->voices[i].midi,&root);k->voices[i].root=root;}sync_notes(k,b,p);float sr=(float)k->rate;float brightness=clamp(p[DNA_BRIGHTNESS]+(p[DNA_TONE_X]-.5f)*.5f,0,1),cutoff=400+brightness*15000;float coefficient=1-expf(-TAU*MIN(cutoff,sr*.45f)/sr);for(uint32_t frame=0;frame<frames;frame++){float sum=0;for(int j=0;j<VOICES;j++){Voice*v=&k->voices[j];if(v->slot<0)continue;const Anchor*a=v->anchor;float attack=(a?a->attack:.015f)*(1.5f-p[DNA_ATTACK]);float release=(a?a->release:.15f)*(1.5f-p[DNA_ARTICULATION]);if(v->releasing)v->envelope*=expf(-1/(release*sr*.2f));else v->envelope=MIN(1,v->envelope+1/(MAX(.001f,attack)*sr));if(p[DNA_NOTE_LENGTH]>.01f&&v->age>p[DNA_NOTE_LENGTH])v->releasing=1;if((v->envelope<.0001f&&v->releasing)||(v->struck&&v->age>(a?a->decay:1.3f)*8)){v->slot=-1;continue;}float glide=MAX(.001f,p[DNA_GLIDE]/1000.f);v->hz+=(v->target-v->hz)*(1-exp(-1/(glide*sr)));float bend=atomic_load(&k->slots[v->slot].bend)+p[DNA_PITCH]*p[DNA_BEND_RANGE];float vibrato=(p[DNA_MODULATION]*.6f+MAX(0,p[DNA_MOVEMENT]-.5f)*.08f)*sinf(TAU*5.2*v->age);double hz=v->hz*pow(2,(bend+vibrato)/12.);float x=0;int mode=(int)p[DNA_ENGINE_MODE];int root=v->root;int use_sample=a&&a->sample&&(mode==0?root==v->midi:mode==2?abs(root-v->midi)<=4:mode==3?abs(root-v->midi)<=5:0);if(!use_sample&&v->layer==1&&sinf(TAU*p[DNA_TRILL_RATE]*v->age)>0)hz*=pow(2,p[DNA_TRILL_INTERVAL]/12.);if(use_sample){if(v->position>=a->length-1){v->slot=-1;continue;}uint32_t at=(uint32_t)v->position;float frac=(float)(v->position-at);x=a->sample[at]*(1-frac)+a->sample[at+1]*frac;v->position+=a->rate/sr*hz/(440*pow(2,(root-69)/12.));}else{v->phase+=hz/sr;v->phase-=floor(v->phase);int harmonics=a&&a->harmonic_count?a->harmonic_count:1;float normal=0;for(int h=1;h<=harmonics&&hz*h<sr*.48;h++){float amp=a&&a->harmonic_count?a->harmonics[h-1]:1;float weight=h==1?amp:amp*MAX(0,1+2*(p[DNA_HARMONICS]-.5f)+(p[DNA_TONE_Y]-.5f)+MAX(0,v->velocity-.5f)*.4f);x+=weight*sinf(TAU*v->phase*h);normal+=fabsf(weight);}x/=MAX(1,normal);if(v->layer==1)x*=.7f+.3f*(sinf(TAU*p[DNA_TRILL_RATE]*v->age)>0);x+=MAX(0,p[DNA_RESONANCE]-.5f)*.08f*sinf(TAU*v->phase);if(v->struck)x*=expf(-v->age/MAX(.04f,a?a->decay:1.3f))*(.7f+p[DNA_BODY]*.6f);}
k->random=k->random*1664525u+1013904223u;float noise=((k->random>>8)/8388608.f-1)*MAX(0,p[DNA_NOISE]-.5f)*.16f*(1+.3f*p[DNA_BEHAVIOR_Y]);x+=noise;float dyn=powf(MAX(.001f,v->velocity),1.4f-.8f*p[DNA_DYNAMICS]);x*=v->envelope*dyn*(.5f+p[DNA_BODY]*.5f);v->filtered+=coefficient*(x-v->filtered);x=v->filtered;float drive=MAX(0,p[DNA_DRIVE]-.5f)*6+MAX(0,p[DNA_BEHAVIOR_X]-.5f)*2*v->velocity;x=tanhf(x*(1+drive))/(1+drive*.3f);sum+=x*.22f;v->age+=1/sr;}float eraAmount=p[DNA_ERA_AMOUNT];float eraCut=p[DNA_ERA]<.5f?20000:p[DNA_ERA]<1.5f?3800:7500;float eraCoef=1-expf(-TAU*MIN(20000*(1-eraAmount)+eraCut*eraAmount,sr*.45f)/sr);k->era_left+=eraCoef*(sum-k->era_left);sum=k->era_left*p[DNA_VOLUME];left[frame]=right[frame]=tanhf(sum);}
atomic_store(&k->hazard,NULL);}
