const A=window.AudioContext||window.webkitAudioContext;const ctx=new A();let buffer=null,sourceText='',events=[],anchors=new Map(),active=new Map();const $=id=>document.getElementById(id);
function midiName(n){return ['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'][n%12]+(Math.floor(n/12)-1)}
function freq(n){return 440*Math.pow(2,(n-69)/12)}
function buildKeys(){for(let n=36;n<=84;n++){let k=document.createElement('div');k.className='key '+([1,3,6,8,10].includes(n%12)?'black':'');k.textContent=midiName(n);k.dataset.n=n;k.onpointerdown=()=>noteOn(n,100,k);k.onpointerup=k.onpointerleave=()=>noteOff(n,k);$('keys').append(k)}}
function nearestAnchor(n){let best=null,d=999;for(const [m,a] of anchors){let q=Math.abs(m-n);if(q<d){d=q;best=a}}return best}
function playSample(n,v){if(!anchors.size)return null;let mode=$('mode').value,a=anchors.get(n);if(mode==='Raw'&&!a)return null;if(!a)a=nearestAnchor(n);if(!a)return null;let s=ctx.createBufferSource(),g=ctx.createGain();s.buffer=a.buffer;s.playbackRate.value=Math.pow(2,(n-a.midi)/12);g.gain.value=Math.max(.03,v/127);s.connect(g).connect(ctx.destination);s.start();return {source:s,gain:g,anchor:a}}
function synth(n,v=100){let o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime;o.frequency.value=freq(n);o.type='triangle';g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(v/127*.18,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+.8);o.connect(g).connect(ctx.destination);o.start();o.stop(t+.85);return {source:o,gain:g}}
function noteOn(n,v,k=document.querySelector('[data-n="'+n+'"]')){ctx.resume();noteOff(n,k);k?.classList.add('active');let voice=playSample(n,v)||synth(n,v);active.set(n,voice);let a=voice.anchor,prov=a?(a.midi===n?'EXTRACTED':'PITCHED FROM '+midiName(a.midi)):'SYNTH FALLBACK';$('detail').textContent=midiName(n)+' · velocity '+v+' · '+$('mode').value+' · '+prov}
function noteOff(n,k=document.querySelector('[data-n="'+n+'"]')){k?.classList.remove('active');let v=active.get(n);if(v){try{v.gain.gain.cancelScheduledValues(ctx.currentTime);v.gain.gain.setTargetAtTime(.0001,ctx.currentTime,.035);v.source.stop(ctx.currentTime+.18)}catch{}active.delete(n)}}
$('file').onchange=async e=>{let f=e.target.files[0];if(!f)return;buffer=await ctx.decodeAudioData(await f.arrayBuffer());anchors.clear();events=[];draw();$('status').textContent=f.name+' · '+buffer.duration.toFixed(2)+' sec · ready to analyze'};
function draw(){let c=$('wave'),d=devicePixelRatio||1;c.width=c.clientWidth*d;c.height=c.clientHeight*d;let x=c.getContext('2d'),a=buffer.getChannelData(0),step=Math.ceil(a.length/c.width),mid=c.height/2;x.clearRect(0,0,c.width,c.height);x.beginPath();for(let i=0;i<c.width;i++){let mn=1,mx=-1;for(let j=0;j<step;j++){let q=a[i*step+j]||0;mn=Math.min(mn,q);mx=Math.max(mx,q)}x.moveTo(i,mid+mn*mid);x.lineTo(i,mid+mx*mid)}x.strokeStyle='#d7dde3';x.stroke()}
function rms(a,p,n){let q=0;for(let i=0;i<n;i++){let v=a[p+i]||0;q+=v*v}return Math.sqrt(q/n)}
function estimatePitch(a,p,n,sr){let best=0,bestCorr=0,minLag=Math.floor(sr/1800),maxLag=Math.min(Math.floor(sr/55),n/2);for(let lag=minLag;lag<=maxLag;lag++){let c=0,e1=0,e2=0;for(let i=0;i<n-lag;i+=2){let x=a[p+i],y=a[p+i+lag];c+=x*y;e1+=x*x;e2+=y*y}let z=c/Math.sqrt(e1*e2+1e-12);if(z>bestCorr){bestCorr=z;best=lag}}return bestCorr>.55?sr/best:0}
function slice(start,end){start=Math.max(0,start);end=Math.min(buffer.length,end);let len=end-start,b=ctx.createBuffer(buffer.numberOfChannels,len,buffer.sampleRate);for(let ch=0;ch<buffer.numberOfChannels;ch++)b.copyToChannel(buffer.getChannelData(ch).slice(start,end),ch);return b}
$('analyze').onclick=()=>{if(!buffer)return $('status').textContent='Choose an audio file first.';sourceText=$('source').value||'unspecified instrument';events=[];anchors.clear();let a=buffer.getChannelData(0),sr=buffer.sampleRate,win=2048,hop=512,gate=.025,was=false,onset=0,candidates=[];
for(let p=0;p+win<a.length;p+=hop){let level=rms(a,p,win),now=level>gate;if(now&&!was)onset=p;if(now){let hz=estimatePitch(a,p,win,sr);if(hz>55&&hz<1800)candidates.push({p,hz,level,onset})}if(!now&&was&&candidates.length){commit(candidates,p,sr)}if(!now)candidates=[];was=now}if(candidates.length)commit(candidates,a.length,sr);
function commit(c,end,sr){let hist=new Map();for(let x of c){let n=Math.round(69+12*Math.log2(x.hz/440));if(n>=36&&n<=84){let old=hist.get(n)||{count:0,power:0};old.count++;old.power+=x.level;hist.set(n,old)}}if(!hist.size)return;let [n,stat]=[...hist].sort((x,y)=>y[1].count-x[1].count)[0],start=Math.max(0,c[0].onset-Math.floor(.01*sr)),finish=Math.min(end,start+Math.floor(Math.min(3,Math.max(.18,(end-start)/sr))*sr)),conf=Math.min(.99,.5+stat.count/Math.max(1,c.length)*.49),obj={midi:n,note:midiName(n),start:start/sr,end:finish/sr,confidence:conf,buffer:slice(start,finish)};events.push(obj);let old=anchors.get(n);if(!old||obj.confidence>old.confidence)anchors.set(n,obj)}
document.querySelectorAll('.key').forEach(k=>{k.classList.remove('extracted','reconstructed');let n=+k.dataset.n;if(anchors.has(n))k.classList.add('extracted');else if(anchors.size&&Math.min(...[...anchors.keys()].map(q=>Math.abs(q-n)))<=5)k.classList.add('reconstructed')});$('status').textContent='Extracted '+events.length+' note events / '+anchors.size+' playable anchors from '+sourceText+'. MIDI now plays extracted audio; nearby notes use nearest-anchor pitch shifting.'};
$('export').onclick=()=>{let dna={version:'0.2',source:sourceText,created:new Date().toISOString(),anchors:[...anchors.values()].map(a=>({midi:a.midi,note:a.note,start:a.start,end:a.end,confidence:+a.confidence.toFixed(3),provenance:'extracted'}))};let u=URL.createObjectURL(new Blob([JSON.stringify(dna,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='instrument-dna.json';a.click();URL.revokeObjectURL(u)};
async function midi(){if(!navigator.requestMIDIAccess)return $('midi').textContent='MIDI: unsupported';try{let m=await navigator.requestMIDIAccess();let bind=()=>{m.inputs.forEach(i=>i.onmidimessage=e=>{let[s,n,v]=e.data,t=s&240;if(t===144&&v)noteOn(n,v);else if(t===128||(t===144&&!v))noteOff(n)});$('midi').textContent='MIDI: '+m.inputs.size+' input'+(m.inputs.size===1?'':'s')};bind();m.onstatechange=bind}catch{$('midi').textContent='MIDI: permission needed'}}
buildKeys();midi();