import {emptyReflection,importReflection,serializable,modelAt,midiName,MACROS,clamp,value} from './dna.js';
import {analyzeBuffer} from './analyzer.js';
import {decodeAudioFile} from './audio-import.js';
const A=window.AudioContext||window.webkitAudioContext,ctx=new A(),$=id=>document.getElementById(id);let dna=emptyReflection(),buffer=null,clips=new Map(),active=new Map(),compare='B';let pending=new Map();const audioState=message=>$('audioStatus').textContent=`Audio: ${message} (context ${ctx.state}, ${ctx.sampleRate} Hz)`;ctx.onstatechange=()=>{if($('audioStatus').textContent.includes('waiting for a click'))audioState('state changed')};
const frequency=n=>440*2**((n-69)/12);
function slice(start,end){let s=Math.max(0,Math.floor(start*buffer.sampleRate)),e=Math.min(buffer.length,Math.ceil(end*buffer.sampleRate)),b=ctx.createBuffer(buffer.numberOfChannels,e-s,buffer.sampleRate);for(let c=0;c<buffer.numberOfChannels;c++)b.copyToChannel(buffer.getChannelData(c).subarray(s,e),c);return b}
function draw(){let c=$('wave'),d=window.devicePixelRatio||1;c.width=c.clientWidth*d;c.height=c.clientHeight*d;let x=c.getContext('2d'),a=buffer.getChannelData(0),step=Math.ceil(a.length/c.width),mid=c.height/2;x.clearRect(0,0,c.width,c.height);x.beginPath();for(let i=0;i<c.width;i++){let mn=1,mx=-1;for(let j=0;j<step;j++){let q=a[i*step+j]||0;mn=Math.min(mn,q);mx=Math.max(mx,q)}x.moveTo(i,mid+mn*mid);x.lineTo(i,mid+mx*mid)}x.strokeStyle='#e7b568';x.stroke()}
function refresh(){document.querySelectorAll('.key').forEach(k=>{let n=+k.dataset.n;k.classList.toggle('extracted',clips.has(n));k.classList.toggle('reconstructed',!clips.has(n)&&!!modelAt(dna,n))});$('expert').replaceChildren();let table=document.createElement('table');table.innerHTML='<tr><th>Anchor</th><th>Pitch confidence</th><th>Attack</th><th>Brightness</th><th>Slice available</th></tr>';for(let a of dna.anchors){let tr=document.createElement('tr');for(let cell of [midiName(a.midi),(a.confidence?.pitch??0).toFixed(2),(a.parameters?.attackSeconds?.analyzed??0).toFixed(3),(a.parameters?.brightness?.analyzed??0).toFixed(2),clips.has(a.midi)?'yes':'no']){let td=document.createElement('td');td.textContent=cell;tr.append(td)}table.append(tr)}$('expert').append(table);renderAdvanced();renderMacros();renderXY()}
function nearest(n){return [...dna.anchors].sort((a,b)=>Math.abs(a.midi-n)-Math.abs(b.midi-n))[0]}
function eraOutput(node){let preset=$('era').value,amount=+$('eraAmount').value;if(preset==='none'||!amount){node.connect(ctx.destination);return}let filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=20000*(1-amount)+(preset==='vintage'?3800:7500)*amount;node.connect(filter).connect(ctx.destination)}
function play(n,v){let m=modelAt(dna,n);if(!m)return {error:'Analyze or load a DNA Reflection first'};let exact=clips.has(n),anchor=nearest(n),mode=$('mode').value;if(mode==='Raw'&&!exact)return {error:`No raw slice for ${midiName(n)}`};let source,gain=ctx.createGain(),tone=ctx.createBiquadFilter();tone.type='lowpass';let bright=clamp((m.parameters.brightness??.5)+((dna.macros.Brightness-.5)*.75)+(dna.xy.tone[0]-.5)*.6);tone.frequency.value=450+bright*15000;let intensity=v/127;gain.gain.value=0;let now=ctx.currentTime,attack=clamp((m.parameters.attackSeconds??.02)*(1.5-dna.macros.Attack),.002,.3),sustain=clamp(intensity*(.4+dna.macros.Dynamics*.6));gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(sustain,now+attack);if(mode==='Raw'||mode==='Hybrid'&&clips.size){let chosen=exact?n:anchor.midi,clip=clips.get(chosen);if(clip){source=ctx.createBufferSource();source.buffer=clip;source.playbackRate.value=2**((n-chosen)/12);source.connect(tone)}else if(mode==='Raw')return {error:'This preset has no embedded audio slices'}}if(!source){source=ctx.createOscillator();source.type='sawtooth';source.frequency.value=frequency(n);source.connect(tone)}tone.connect(gain);eraOutput(gain);source.start(now);return {source,gain,anchor,exact,mode:source.buffer?'recorded slice':'modeled oscillator',m}}
async function ready(){if(ctx.state!=='running')await ctx.resume();if(ctx.state!=='running')throw Error(`Audio engine is ${ctx.state}; click Test sound to unlock it`)}
async function noteOn(n,v,k=document.querySelector(`[data-n="${n}"]`)){let token=Symbol();pending.set(n,token);try{await ready();if(pending.get(n)!==token)return;noteOff(n,k,false);let voice=play(n,v);pending.delete(n);if(voice.error){$('detail').textContent=voice.error;audioState('no voice started');return}k?.classList.add('active');active.set(n,voice);$('detail').textContent=`${midiName(n)} · ${voice.mode}${voice.mode==='recorded slice'?` from ${midiName(voice.exact?n:voice.anchor.midi)}`:''} · model confidence ${voice.m.confidence.toFixed(2)}`;audioState(`${voice.mode} started on ${midiName(n)}`);$('recommendation').textContent=voice.m.recommendation||''}catch(e){pending.delete(n);$('detail').textContent=`Playback failed: ${e.message}`;audioState('playback error');console.error('Instrument DNA playback',e)}}
function noteOff(n,k=document.querySelector(`[data-n="${n}"]`),cancelPending=true){if(cancelPending)pending.delete(n);k?.classList.remove('active');let voice=active.get(n);if(!voice)return;let t=ctx.currentTime;voice.gain.gain.cancelScheduledValues(t);voice.gain.gain.setTargetAtTime(.0001,t,.08);try{voice.source.stop(t+.4)}catch{}active.delete(n)}
$('testSound').onclick=async()=>{try{await ready();let source=ctx.createOscillator(),gain=ctx.createGain(),t=ctx.currentTime;source.type='sine';source.frequency.value=440;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(.18,t+.03);gain.gain.setValueAtTime(.18,t+.85);gain.gain.linearRampToValueAtTime(0,t+1);source.connect(gain).connect(ctx.destination);source.start(t);source.stop(t+1.02);audioState('440 Hz test tone started for 1 second');$('detail').textContent='Test sound uses a direct tone and bypasses imported audio and instrument controls.'}catch(e){audioState(`test failed: ${e.message}`);console.error('Instrument DNA test sound',e)}};
for(let n=36;n<=84;n++){let k=document.createElement('div');k.className='key '+([1,3,6,8,10].includes(n%12)?'black':'');k.textContent=midiName(n);k.dataset.n=n;k.onpointerdown=e=>{e.preventDefault();k.setPointerCapture(e.pointerId);noteOn(n,100,k)};k.onpointerup=k.onpointercancel=()=>noteOff(n,k);$('keys').append(k)}
let previewURL=null,importSerial=0;
$('file').onchange=async e=>{let f=e.target.files[0];if(!f)return;let serial=++importSerial;buffer=null;clips.clear();dna=emptyReflection();refresh();$('status').textContent=`Opening ${f.name}…`;if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(f);$('sourcePreview').src=previewURL;$('previewWrap').hidden=false;try{let decoded=await decodeAudioFile(ctx,f,message=>$('status').textContent=message);if(serial!==importSerial)return;buffer=decoded.buffer;draw();$('status').textContent=`${f.name} · ${buffer.duration.toFixed(2)} sec · ${decoded.decoder} decode · ready to analyze`}catch(err){if(serial!==importSerial)return;$('status').textContent=`Audio import failed: ${err.message}`;console.error('Instrument DNA audio import',err)}};
$('analyze').onclick=()=>{if(!buffer){$('status').textContent='Choose an audio file first.';return}dna=emptyReflection();dna.classification.name=$('source').value.trim()||'unspecified instrument';dna.capture.density=+$('density').value;dna.provenance=[{archive:$('archive').value,itemId:$('item').value,recordingDate:$('recordingDate').value,instrument:dna.classification.name,performer:$('performer').value,rightsStatus:$('rights').value||'unverified',url:$('url').value,analysisDate:new Date().toISOString(),analyzerVersion:dna.analyzerVersion,redistributionPermitted:$('redistribute').checked}];let result=analyzeBuffer(buffer,dna);clips.clear();for(let a of dna.anchors)clips.set(a.midi,slice(a.start,a.end));dna.sampleSlots=dna.anchors.map(a=>({role:'attack',anchorMidi:a.midi,pitchFollow:true,formantFollow:false,resonatorFollow:false,filterFollow:false,excitesResonator:false,embedded:false}));$('status').textContent=`${result.events.length} note events · ${dna.anchors.length} unique anchors. Capture target ${dna.capture.density}/octave; add isolated notes to fill gaps.`;refresh()};
$('export').onclick=()=>{let blob=new Blob([JSON.stringify(serializable(dna),null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='instrument-dna-reflection.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
$('import').onchange=async e=>{try{dna=importReflection(JSON.parse(await e.target.files[0].text()));clips.clear();buffer=null;if(previewURL)URL.revokeObjectURL(previewURL);previewURL=null;$('sourcePreview').removeAttribute('src');$('previewWrap').hidden=true;$('status').textContent=`Loaded ${dna.anchors.length} anchors. Reflection contains no audio; reconstructed audition uses the model oscillator.`;$('era').value=dna.era?.recording||'none';$('eraAmount').value=dna.era?.amount||0;refresh()}catch(err){$('status').textContent=`Could not load reflection: ${err.message}`}};
function renderMacros(){let box=$('macros');box.replaceChildren();for(let name of MACROS){let label=document.createElement('label'),input=document.createElement('input');label.textContent=name;input.type='range';input.min=0;input.max=1;input.step=.01;input.value=dna.macros[name]??.5;input.oninput=()=>dna.macros[name]=+input.value;label.append(input);box.append(label)}}
function renderXY(){for(let id of ['tone','behavior']){let pad=$(id),p=dna.xy[id]||[.5,.5],dot=pad.querySelector('span');dot.style.left=`${p[0]*100}%`;dot.style.top=`${(1-p[1])*100}%`}}
for(let id of ['tone','behavior']){let pad=$(id),update=e=>{let r=pad.getBoundingClientRect();dna.xy[id]=[clamp((e.clientX-r.left)/r.width),clamp(1-(e.clientY-r.top)/r.height)];renderXY()};pad.onpointerdown=e=>{pad.setPointerCapture(e.pointerId);update(e)};pad.onpointermove=e=>{if(e.buttons)update(e)};pad.onkeydown=e=>{let p=dna.xy[id];if(e.key==='ArrowRight')p[0]=clamp(p[0]+.02);else if(e.key==='ArrowLeft')p[0]=clamp(p[0]-.02);else if(e.key==='ArrowUp')p[1]=clamp(p[1]+.02);else if(e.key==='ArrowDown')p[1]=clamp(p[1]-.02);else return;e.preventDefault();renderXY()}}
function renderAdvanced(){let box=$('advanced');box.replaceChildren();let button=document.createElement('button');button.textContent=`Compare: ${compare} · ${compare==='B'?'edited':'analyzed'}`;button.onclick=()=>{compare=compare==='A'?'B':'A';for(let p of Object.values(dna.global)){if(compare==='A'){p.savedOffset=p.offset;p.offset=0}else p.offset=p.savedOffset??p.offset}renderAdvanced()};box.append(button);for(let [key,p] of Object.entries(dna.global)){if(typeof p.model!=='number')continue;let label=document.createElement('label'),input=document.createElement('input'),reset=document.createElement('button');label.textContent=`${key} · analyzed ${p.analyzed.toFixed(3)} · confidence ${p.confidence.toFixed(2)} · user offset`;input.type='number';input.step='.01';input.value=p.offset;input.disabled=compare==='A';input.onchange=()=>{p.offset=Number(input.value)||0};reset.textContent='Reset';reset.disabled=compare==='A';reset.onclick=()=>{input.value=0;input.onchange()};label.append(input,reset);box.append(label)}}
$('era').onchange=()=>dna.era.recording=$('era').value;$('eraAmount').oninput=()=>dna.era.amount=+$('eraAmount').value;
async function midi(){if(!navigator.requestMIDIAccess){$('midi').textContent='MIDI: unsupported';return}try{let m=await navigator.requestMIDIAccess(),bind=()=>{m.inputs.forEach(i=>i.onmidimessage=e=>{let[s,n,v]=e.data,t=s&240;if(t===144&&v)noteOn(n,v);else if(t===128||t===144&&!v)noteOff(n)});$('midi').textContent=`MIDI: ${m.inputs.size} inputs`};bind();m.onstatechange=bind}catch{$('midi').textContent='MIDI: permission needed'}}refresh();midi();
