// Browser decode first; small, local fallback decoders load only when necessary.
const decoders={
  mp3:['mpg123-decoder.min.js','mpg123-decoder','MPEGDecoder'],
  flac:['flac-decoder.min.js','flac-decoder','FLACDecoder'],
  vorbis:['ogg-vorbis-decoder.min.js','ogg-vorbis-decoder','OggVorbisDecoder'],
  opus:['ogg-opus-decoder.min.js','ogg-opus-decoder','OggOpusDecoder']
};
const loaded=new Map();
function loadScript(name){if(!loaded.has(name))loaded.set(name,new Promise((resolve,reject)=>{let s=document.createElement('script');s.src=new URL(`../vendor/decoders/${name}`,import.meta.url);s.charset='UTF-8';s.onload=resolve;s.onerror=()=>reject(Error(`Could not load ${name}`));document.head.append(s)}));return loaded.get(name)}
function pcmBuffer(ctx,result){const {channelData,sampleRate}=result;if(!channelData?.length||!sampleRate||!channelData[0]?.length)throw Error('Decoder returned no audio');const b=ctx.createBuffer(channelData.length,channelData[0].length,sampleRate);channelData.forEach((ch,i)=>b.copyToChannel(ch,i));return b}
function signature(data){const s=new TextDecoder('latin1').decode(data.subarray(0,256));if(s.startsWith('fLaC')||s.startsWith('OggS')&&s.includes('fLaC'))return 'flac';if(s.startsWith('OggS'))return s.includes('OpusHead')?'opus':'vorbis';if(s.startsWith('FORM')&&['AIFF','AIFC'].includes(s.slice(8,12)))return 'aiff';if(s.startsWith('ID3')||data[0]===255&&data[1]>=224)return 'mp3';return null}
function decodeExtended(v,p){const sign=v.getUint8(p)&128?-1:1,exp=((v.getUint8(p)&127)<<8)|v.getUint8(p+1),hi=v.getUint32(p+2),lo=v.getUint32(p+6);return exp===0&&hi===0&&lo===0?0:sign*(hi*2**32+lo)*2**(exp-16383-63)}
export function decodeAiff(ctx,bytes){const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),str=(p,n)=>String.fromCharCode(...bytes.subarray(p,p+n));if(str(0,4)!=='FORM'||!['AIFF','AIFC'].includes(str(8,4)))throw Error('Not an AIFF file');let channels=0,frames=0,bits=0,rate=0,offset=-1,size=0,little=false;for(let p=12;p+8<=bytes.length;){let tag=str(p,4),len=v.getUint32(p+4),start=p+8;if(start+len>bytes.length)throw Error('Truncated AIFF chunk');if(tag==='COMM'){if(len<18)throw Error('Invalid AIFF header');channels=v.getUint16(start);frames=v.getUint32(start+2);bits=v.getUint16(start+6);rate=decodeExtended(v,start+8);if(str(8,4)==='AIFC'){let compression=str(start+18,4);if(!['NONE','sowt'].includes(compression))throw Error(`Unsupported AIFF compression ${compression}`);little=compression==='sowt'}}if(tag==='SSND'){if(len<8)throw Error('Invalid AIFF sound data');offset=start+8+v.getUint32(start);size=len-8-v.getUint32(start)}p=start+len+(len%2)}if(!channels||channels>8||!rate||rate>192000||!frames||!size||offset<0||![8,16,24,32].includes(bits))throw Error('Unsupported or empty PCM AIFF');let width=bits/8,count=Math.min(frames,Math.floor(size/(width*channels)));if(count<=0)throw Error('Empty AIFF sound data');let out=ctx.createBuffer(channels,count,Math.round(rate));for(let c=0;c<channels;c++){let dst=out.getChannelData(c);for(let i=0;i<count;i++){let pos=offset+(i*channels+c)*width,val=0;if(width===1)val=v.getInt8(pos)/128;else if(width===2)val=v.getInt16(pos,little)/32768;else if(width===4)val=v.getInt32(pos,little)/2147483648;else{let a=v.getUint8(pos),b=v.getUint8(pos+1),d=v.getUint8(pos+2);val=(little?(d<<16|b<<8|a):(a<<16|b<<8|d));if(val&0x800000)val-=0x1000000;val/=8388608}dst[i]=val}}return out}
export async function decodeAudioFile(ctx,file,onProgress=()=>{}){const data=new Uint8Array(await file.arrayBuffer());if(!data.length)throw Error('The selected file is empty');let nativeError;try{return {buffer:await ctx.decodeAudioData(data.buffer.slice(0)),decoder:'browser'}}catch(e){nativeError=e}
const type=signature(data),ext=file.name.split('.').pop()?.toLowerCase();if(type==='aiff'||['aif','aiff','aifc'].includes(ext)){try{return {buffer:decodeAiff(ctx,data),decoder:'PCM AIFF'}}catch(e){throw Error(`${e.message}. Browser decoder also failed: ${nativeError.message}`)}}
const key=type||({mpeg:'mp3',oga:'vorbis',ogg:'vorbis',opus:'opus',flac:'flac',mp3:'mp3'})[ext];if(!decoders[key])throw Error(`This browser cannot decode ${ext?.toUpperCase()||'this file'}; try uncompressed WAV, MP3, AAC/M4A, FLAC, Ogg or PCM AIFF. (${nativeError.message})`);
onProgress(`Loading ${key.toUpperCase()} fallback decoder…`);let [script,globalName,className]=decoders[key];await loadScript(script);let Decoder=window[globalName]?.[className];if(!Decoder)throw Error(`${key.toUpperCase()} decoder did not initialize`);let decoder=new Decoder();try{await decoder.ready;let result=decoder.decode(data);if(result.errors?.length&&(!result.samplesDecoded||!result.channelData?.[0]?.length))throw Error(result.errors.join('; '));return {buffer:pcmBuffer(ctx,result),decoder:`${key.toUpperCase()} fallback`}}finally{decoder.free()}}
