export const VERSION='0.3.0';
export const DENSITIES=[1,3,6,12];
export const MACROS=['Attack','Body','Brightness','Harmonics','Noise','Resonance','Dynamics','Articulation','Movement','Drive'];
export const midiName=n=>['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'][((n%12)+12)%12]+(Math.floor(n/12)-1);
export const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
export function emptyReflection(){return {format:'instrument-dna-reflection',version:VERSION,analyzerVersion:VERSION,created:new Date().toISOString(),classification:{name:'unspecified',family:'unknown'},provenance:[],capture:{density:3,range:null},global:{},registers:[],anchors:[],performance:{velocity:{},articulations:[],modulation:{}},sampleSlots:[],era:{instrument:null,recording:null,amount:0},macros:Object.fromEntries(MACROS.map(x=>[x,0.5])),xy:{tone:[0.5,0.5],behavior:[0.5,0.5]},extensions:{}}}
export function param(analyzed,confidence=0,unit='normalized'){return {analyzed,model:analyzed,offset:0,confidence:clamp(confidence),unit}}
export function value(p){return (p?.model??0)+(p?.offset??0)}
export function interpolate(a,b,t){return a+(b-a)*clamp(t)}
export function modelAt(dna,n){const list=[...dna.anchors].sort((a,b)=>a.midi-b.midi);if(!list.length)return null;let left=list.filter(a=>a.midi<=n).at(-1),right=list.find(a=>a.midi>=n);left??=list[0];right??=list.at(-1);let t=left===right?0:(n-left.midi)/(right.midi-left.midi),reg=dna.registers.find(r=>n>=r.from&&n<=r.to);let fields={};const keys=new Set([...Object.keys(dna.global),...Object.keys(reg?.parameters||{}),...Object.keys(left.parameters||{}),...Object.keys(right.parameters||{})]);for(const key of keys){let g=dna.global[key],r=reg?.parameters?.[key],l=left.parameters?.[key],h=right.parameters?.[key];if(Array.isArray(l?.model)&&Array.isArray(h?.model))fields[key]=l.model.map((v,i)=>interpolate(v,h.model[i]??v,t));else if(typeof l?.model==='number'&&typeof h?.model==='number')fields[key]=interpolate(value(l),value(h),t);else fields[key]=value(l??h??r??g)}let gap=Math.min(Math.abs(n-left.midi),Math.abs(n-right.midi));let base=Math.min(left.confidence?.overall??0,right.confidence?.overall??0);return {midi:n,parameters:fields,confidence:clamp(base*(1-gap/12)),recommendation:gap>=4||base<.5?`Additional reference sample recommended near ${midiName(n)}.`:null,anchors:[left.midi,right.midi],register:reg?.name??null}}
export function buildHierarchy(dna){let a=dna.anchors;if(!a.length){dna.global={};dna.registers=[];dna.capture.range=null;return dna}dna.capture.range=[Math.min(...a.map(x=>x.midi)),Math.max(...a.map(x=>x.midi))];let keys=['attackSeconds','decaySeconds','releaseSeconds','brightness','noise','inharmonicity','resonance','harmonicRichness'];function mean(items){let o={};for(let key of keys){let vals=items.map(x=>x.parameters[key]?.analyzed).filter(Number.isFinite);if(vals.length)o[key]=param(vals.reduce((s,x)=>s+x,0)/vals.length,Math.min(...items.map(x=>x.confidence.overall)))}return o}dna.global=mean(a);let groups=new Map();for(let x of a){let octave=Math.floor(x.midi/12)-1;if(!groups.has(octave))groups.set(octave,[]);groups.get(octave).push(x)}dna.registers=[...groups].map(([octave,items])=>({name:`octave ${octave}`,from:(octave+1)*12,to:(octave+2)*12-1,parameters:mean(items),anchorPitches:items.map(x=>x.midi)}));return dna}
export function serializable(dna){let clean=structuredClone(dna);for(let a of clean.anchors){delete a.buffer;delete a.audioData}for(let s of clean.sampleSlots){delete s.buffer;delete s.audioData}return clean}
export function validateReflection(d){if(!d||d.format!=='instrument-dna-reflection'||!Array.isArray(d.anchors)||!Array.isArray(d.provenance)||!Array.isArray(d.sampleSlots))throw Error('Invalid DNA Reflection');if(d.anchors.some(a=>!Number.isInteger(a.midi)||a.midi<0||a.midi>127))throw Error('Invalid anchor pitch');return d}
export function importReflection(d){return validateReflection(structuredClone(d))}
